# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"  # Using 3.9 for better compatibility with dependencies

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Don't fail on warnings during development

# Python requirements for building documentation
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Additional formats
formats:
  - htmlzip
  - pdf
  - epub

# Submodules
submodules:
  include: all
  recursive: true
